name: run test.py

on:
  schedule:
    - cron: '0 12 * * 1' # At 12:00 every Monday
  pull_request:
    types:
      - opened
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      
env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
  DISCOVER_WEEKLY_ID: ${{ secrets.DISCOVER_WEEKLY_ID }}
  PERSONAL_PLAYLIST_ID: ${{ secrets.PERSONAL_PLAYLIST_ID }}
  LIKE_PLAYLIST_ID: ${{ secrets.LIKE_PLAYLIST_ID }}
  DISLIKE_PLAYLIST_ID: ${{ secrets.DISLIKE_PLAYLIST_ID }}
  PREDICTED_LIKE_ID: ${{ secrets.PREDICTED_LIKE_ID }}
  PREDICTED_DISLIKE_ID: ${{ secrets.PREDICTED_DISLIKE_ID }}  
  GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: fetch and write to BQ # run test.py
        run: python test.py